//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public string invoice_id { get; set; }
        public System.DateTime invoice_date { get; set; }
        public string appointment_id { get; set; }
        public System.DateTime invoice_time_generated { get; set; }
        public decimal invoice_amount { get; set; }
        public decimal invoice_discount { get; set; }
        public decimal invoice_paid_amount { get; set; }
        public System.DateTime invoice_paid_time { get; set; }
        public string payment_type { get; set; }
    }
}
