//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public string medicine_id { get; set; }
        public string medicine_Sc_name { get; set; }
        public string medicine_name { get; set; }
        public string medicine_type { get; set; }
        public string medicine_unit { get; set; }
        public string medicine_purchase_price { get; set; }
        public string medicine_price { get; set; }
        public string medicine_instore_quantity { get; set; }
        public string medicine_min_quantity { get; set; }
        public string medicine_coo { get; set; }
        public System.DateTime medicine_expiry_date { get; set; }
    }
}
