//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner
    {
        public string owner_id { get; set; }
        public string owner_name { get; set; }
        public string owner_mobile { get; set; }
        public string owner_phone { get; set; }
        public string owner_email { get; set; }
        public string owner_address { get; set; }
    }
}
