//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public string pet_id { get; set; }
        public string pet_name { get; set; }
        public string owner_id { get; set; }
        public byte[] pet_photo { get; set; }
        public System.DateTime pet_dob { get; set; }
        public string pet_species { get; set; }
        public string pet_breeds { get; set; }
        public string notes { get; set; }
    }
}
