//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public string service_id { get; set; }
        public string service_name { get; set; }
        public string unit_id { get; set; }
        public decimal cost_per_unit { get; set; }
    }
}
