//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_commercial_registration { get; set; }
        public System.DateTime supplier_CR_expiry_date { get; set; }
        public string supplier_email { get; set; }
        public string supplier_address { get; set; }
        public string supplier_mobile { get; set; }
        public string supplier_phone { get; set; }
        public string supplier_bank_account { get; set; }
    }
}
